### ISSUE TITLE
[specification] add e2e basic specification to document/specification directory

### ISSUE THREAD

**Issue by opionoid** [RinUeyama/ratlis-the-northern-ruin#1]
## TODO

- [x] add docsify
- [ ] write document that shows process from top to battle
- [ ] doc - main - what is this game - deep dive mapping - restart to enchantment character
- [ ] doc - story
- [ ] doc - top
- [x] doc - map
- [ ] doc - situation (rename?)
- [x] doc - battle
- [x] doc - enchantment - equipment
- [ ] doc - enchantment -  skill
- [x] doc - enchantment - bless
- [x] doc - enchantment - map (rename?)
- [ ] doc - config
